version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.17.16
    # build:
    #   context: .
    #   dockerfile: Dockerfile-elastic
    container_name: elasticsearch
    group_add:
      - 0
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/elk_data/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/elk_data/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ~/elk_data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elastic_config:/usr/share/elasticsearch/config
    logging:
        driver: "json-file"
        options:
            max-size: "10k"
            max-file: "10"
  kibana:
    image: kibana:7.17.16
    restart: on-failure
    container_name: kibana
    group_add:
      - 0
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=0.0.0.0"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
